<a href="https://colab.research.google.com/github/rawatpremsingh999/tensorflow-coursera/blob/master/coursera_4203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [7]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1)

for window_data in dataset:
  for val in window_data:
    print(val.numpy(), end = " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [8]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1, drop_remainder=True)

for window_data in dataset:
  for val in window_data:
    print(val.numpy(), end = " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

for x, y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)

for x, y in dataset:
  print(x.numpy(), y.numpy())

[2 3 4 5] [6]
[1 2 3 4] [5]
[0 1 2 3] [4]
[4 5 6 7] [8]
[5 6 7 8] [9]
[3 4 5 6] [7]


In [17]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(size = 5, shift= 1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

for x, y in dataset:
  print("x= ", x.numpy())
  print("y= ", y.numpy())

x=  [[0 1 2 3]
 [5 6 7 8]]
y=  [[4]
 [9]]
x=  [[4 5 6 7]
 [3 4 5 6]]
y=  [[8]
 [7]]
x=  [[2 3 4 5]
 [1 2 3 4]]
y=  [[6]
 [5]]
